### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by joeross** [microdotblog/theme-gateway#2]
I don't know if I did something to mess it up or if the icon font/source is borked. ![image](https://user-images.githubusercontent.com/796145/216847970-e67e2492-e90c-412f-9fee-3abdaec50039.png)

**Comment by manton** [comment]
Thanks @joeross. I inadvertently broke these icons. I've updated the plug-in to load the icons directly and it should be working now, but will require updating to the latest version of the plug-in. It takes Micro.blog 1-2 hours to notice the new version. When it's ready, you should see an "Upgrade" button on the Plug-ins page that will install the fix.
